services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  
  api:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Demo.Redis.WebApi/Dockerfile
    environment:
      ConnectionStrings__Postgres: "Host=postgres:5432;Username=postgres;Password=password;Database=postgres"
    ports:
      - 5109:80
      - 7232:443